In [2]:
import numpy as np

In [8]:
arr = np.random.randint(0, 10, size=(9, 9))

In [9]:
arr

array([[9, 2, 3, 1, 1, 1, 0, 7, 3],
       [7, 4, 8, 7, 6, 9, 7, 9, 7],
       [4, 2, 3, 4, 4, 0, 4, 5, 2],
       [7, 3, 1, 3, 5, 5, 6, 3, 8],
       [5, 0, 7, 6, 9, 3, 3, 6, 1],
       [5, 4, 1, 0, 7, 6, 7, 8, 4],
       [6, 0, 6, 4, 4, 5, 4, 1, 9],
       [2, 5, 9, 1, 9, 2, 3, 5, 2],
       [3, 7, 5, 9, 5, 1, 1, 2, 2]])

In [12]:
shape=arr.shape
shape

(9, 9)

In [15]:
row=shape[0]
col=shape[1]

In [18]:
row,col

(9, 9)

In [25]:
for i in range(0,row-2,3):
    for j in range(0,col-2,3):
        slice=arr[i:i+3,j:j+3]
        print(slice)

[[9 2 3]
 [7 4 8]
 [4 2 3]]
[[1 1 1]
 [7 6 9]
 [4 4 0]]
[[0 7 3]
 [7 9 7]
 [4 5 2]]
[[7 3 1]
 [5 0 7]
 [5 4 1]]
[[3 5 5]
 [6 9 3]
 [0 7 6]]
[[6 3 8]
 [3 6 1]
 [7 8 4]]
[[6 0 6]
 [2 5 9]
 [3 7 5]]
[[4 4 5]
 [1 9 2]
 [9 5 1]]
[[4 1 9]
 [3 5 2]
 [1 2 2]]
